### ISSUE TITLE
Core: Input string \"null\" is not a valid UUID with previousSessionId on Android Versions lower than KitKat

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-android-tracker#185] opened 2016-02-24 16:59 UTC
Moving this over from #176.

**Comment by bernardosrulzon** [comment] 2016-02-24 17:05
@jbeemster I can provide some real-life JSONs that failed this validation, if that helps your debugging in any way

**Comment by alexanderdean** [comment] 2016-02-24 17:06
Thanks @bernardosrulzon ! If we can verify this behavior we will obviously bring this fix forward into a patch release.

**Comment by jbeemster** [comment] 2016-02-24 17:20
Hi @bernardosrulzon yes if you could provide sample JSONs that would be very helpful!

**Comment by bernardosrulzon** [comment] 2016-02-24 17:30
@jbeemster here's a couple, let me know if you need more: https://gist.github.com/bernardosrulzon/56efe0437f8bcd69c3a0

btw - these contexts were generated by the last version of our app, which uses the latest version of the android tracker

**Comment by alexanderdean** [comment] 2016-02-24 17:31
Bringing forwards

**Comment by jbeemster** [comment] 2016-02-25 12:49
Hi @bernardosrulzon so in testing what is coming directly out of the Tracker using the Demo Application I am seeing the correct `null` rather then `"null"`.  

A few more questions to help us get to the bottom of this:

* Are you using the base64 encoding option for the Tracker?  
* Are you sending events via GET or POST?
* Would you mind sharing the full event payload in the raw format from the collector?

**Comment by bernardosrulzon** [comment] 2016-02-25 13:29
@jbeemster Hmmm, I could also not replicate this on my own device. We're using POST, and I tested with base64 enabled and disabled - both returned the expected `null`. I have some new insights, though:

- In the wild, ~15% of Android events are being sent with `"null"`
- In all of the above cases, the OS version was <=4.3

![image](https://cloud.githubusercontent.com/assets/6955526/13320788/fc1b51ac-dba9-11e5-8448-9c19d762b793.png)

If you want to dig deeper into this, please check the complete dataset and query: https://gist.github.com/bernardosrulzon/fcb1db6aa805ae5661b6

**Comment by jbeemster** [comment] 2016-02-25 13:42
I feel like this might relate back to this function: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Util.java#L113-L156

This was contributed a while ago as a way of removing a JSON library but seems to not be working properly to parse below version 4.4.  Looks like we might need to revert back to using an external library or to fix that function to work for lower versions.

Looks like this return is what might be the culprit: https://github.com/snowplow/snowplow-android-tracker/blob/0.5.3/snowplow-android-core/src/main/java/com/snowplowanalytics/snowplow/tracker/utils/Util.java#L122 in that it is returning` "null"` rather than `null`.

**Comment by jbeemster** [comment] 2016-02-25 13:57
Confirmed this is an error below API Level 19.

**Comment by jbeemster** [comment] 2016-02-25 14:26
@bernardosrulzon thanks so much for the data set, really helped in narrowing down this bug.  From my local testing it looks the change I have pushed fixes the issue and returns the correct null for lower API versions.

**Comment by bernardosrulzon** [comment] 2016-02-25 14:49
No problem, Snowplow is awesome and I'm glad to help in any way I can! :)

**Closed** 2016-03-02 05:38 UTC
Labels: bug

**Comment by MoizAli** [comment] 2016-03-04 10:34
Why is this bug closed? I can still see it happening.

**Comment by jbeemster** [comment] 2016-03-04 10:38
Hi @MoizAli thats very strange!  Could you please give me some more information on the Android device levels this is occurring on?
