### ISSUE TITLE
Repeat same data in successive calls

### ISSUE THREAD

**Issue by JoseFelixCastillo** [snowplow/snowplow-android-tracker#316] opened 2019-07-09 12:03 UTC
When i send successive events, the global parameters like applicationContext are repeating, because they accumulate in the instance. 
I saw de code, and i think the problem is when it is checked the boolean of those parameters is added to array, when it should be added if it does not exist only. 
For that i need to clearGlobalContext before send each event, but i think is not good solution. Also in automatically events like "lifecycleEvents" they accumulate because y cant clearGlobalContext.

How can i manage that?

**Comment by djohannot** [comment] 2019-07-22 05:40
I have the same issue, it grows till 500 global context...... the only solution i found was to have a synchronize access to my tracker, call clear before and send the event, but it's definitely an implementation error, especially because it's specified nowhere that we have to do it in the doc

**Comment by djohannot** [comment] 2019-07-22 06:36
even with my fix it doesn't work, one of the issue is the ` Executor.execute(new Runnable() ` in the tracker that is not thread safe, therefore unless i modify manually this class there is no way to use this version of the tracker in our company...

**Comment by luisfernandezbr** [comment] 2019-07-22 18:04
Hi guys. We are having the same problem. Seems that all library "entities" are increasing every time new event sent. Downgrading to the previous 1.1.0 version.

**Comment by oguzhanunlu** [comment] 2019-07-23 14:06
Hey @JoseFelixCastillo , @luisfernandezbr , thanks for the report. We're aware that there is a critical bug with the latest tracker version. Please downgrade to a prior version until we fix this. It went unnoticed due to not having proper tests and we're working on improving our test suite. The next release will include new test suite and the bug fix.

Sorry for the inconvenience and thanks for the understanding.

**Comment by JoseFelixCastillo** [comment] 2019-07-26 08:48
@oguzhanunlu the problem right now, is that if i downgrade the version, is not sending events for some devices, like a sony Xperia with 5.0 or a Huawei with 6.0. So i cant downgrade version.

**Comment by YSDC** [comment] 2019-07-26 08:51
I did a fix in a fork here https://github.com/djohannot/snowplow-android-tracker/tree/bugfix/duplicate-globalcontexts

Select the bug fix branch and Tulle me if it works for you, it did for me. I did a PR to merge it but in the meantime it might help you. You will need to either deploy in a local repo or add directly the AAR

**Comment by oguzhanunlu** [comment] 2019-07-30 13:09
Please see https://github.com/snowplow/snowplow-android-tracker/issues/314#issuecomment-516409106 for an explanation in detail.

**Comment by oguzhanunlu** [comment] 2019-07-30 13:58
Closing the ticket due to multiple issues referring to the same bug. #314 is included in upcoming `1.2.1` patch release.

**Closed by oguzhanunlu** 2019-07-30 13:58 UTC
