### ISSUE TITLE
Issue getting SSL to work with sample code

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/snowplow-android-tracker#197] opened 2016-04-21 11:04 UTC
From a client:

> We had some problems getting SSL to work using your sample code. We fixed is eventually, but it cost us a day or two. I thought you might like to know what it was. Our collector servers are strictly configured to use only the latest and greatest SSL ciphers. I don't know how common this is, but we found that the sample app could not connect to our collector due to an SSL error. We fixed this by upgrading the okhttp library to 2.7.5. In this link, it is recommending version 2.1.0.

https://github.com/snowplow/snowplow/wiki/Android-Tracker-Setup#classic*

**Comment by jbeemster** [comment] 2016-06-20 14:30
On the move to OkHttp3 this will be addressed. Closing as duplicate of https://github.com/snowplow/snowplow-android-tracker/pull/183

**Closed by jbeemster** 2016-06-20 14:30 UTC
Labels: enhancement
