### ISSUE TITLE
use contexts/jsonschema/1-0-0 to allow empty custom contexts

### ISSUE THREAD

**Issue by leonmaas** [snowplow/snowplow-android-tracker#246] opened 2017-05-24 10:03 UTC
1-0-1 does not allow for empty custom contexts causing the events to end in the bad rows. Most trackers seem to use 1-0-0 for this reason. Stripping ([like here](https://github.com/snowplow/snowplow-ruby-tracker/issues/104)) is fine too.

**Comment by alexanderdean** [comment] 2017-05-24 10:20
I don't think that a 1-0-1 would be more restrictive than a 1-0-0 - if it is, then we have failed with the versioning of that schema. Can you take another look @leonmaas ?

**Comment by alexanderdean** [comment] 2018-02-22 22:37
Talk to me when you get to this one!

**Comment by mhadam** [comment] 2018-04-20 17:05
The tracker [doesn't send empty contexts][1], unless the issue is that someone is adding a custom context that doesn't have a data field?

[1]: https://github.com/snowplow/snowplow-android-tracker/blob/master/snowplow-tracker/src/main/java/com/snowplowanalytics/snowplow/tracker/Tracker.java#L453

**Comment by alexanderdean** [comment] 2018-04-21 21:09
I don't understand this one:

* As Mike says, the tracker won't send empty contexts
* The 1-0-1 is more permissive than the 1-0-0, as it removes the `"minItems": 1` constraint

De-scheduling and closing.

**Closed by alexanderdean** 2018-04-21 21:09 UTC
Labels: bug
