### ISSUE TITLE
addGlobalContext not working

### ISSUE THREAD

**Issue by SzotsLevente** [snowplow/snowplow-android-tracker#338] opened 2019-10-30 08:11 UTC
val dataMap: HashMap<String, Any> = HashMap()

        dataMap["device"] = "Android"
        dataMap["locale"] = getCurrentLocale(this).language

val globalContext = SelfDescribingJson("iglu:eu.test/global_context/jsonschema/1-0-0 ", dataMap)

tracker.addGlobalContext(globalContext)

and after this i'm calling a screenview builder and the event doesn't seems to be sent, if i remove the addGlobalContext line it works perfectly, is there something that i'm not using how it supposed to?

@oguzhanunlu @jbeemster

**Comment by oguzhanunlu** [comment] 2019-10-30 09:53
Thanks for the report @SzotsLevente , I'll look at it and get back as soon as possible.

**Comment by SzotsLevente** [comment] 2019-10-31 06:30
object SnowplowTracker {

    fun getTracker(context: Context): Tracker {
        Tracker.close()

        val emitter = getEmitter(context)
        val subject = getSubject(context) // Optional

        return Tracker.init(Tracker.TrackerBuilder(emitter, context.getString(R.string.tracker_namespace), context.getString(R.string.app_id), context)
                .level(LogLevel.VERBOSE)
                .base64(false)
                .threadCount(20)
                .sessionContext(true)
                .mobileContext(true)
                .applicationCrash(true)
                .lifecycleEvents(true)
                .foregroundTimeout(60)
                .backgroundTimeout(30)
                .screenviewEvents(true)
                .screenContext(true)
                .installTracking(true)
                .applicationContext(false)
                .subject(subject) // Optional
                .build()
        )
    }

    private fun getEmitter(context: Context): Emitter {
        return Emitter.EmitterBuilder(context.getString(R.string.tracker_uri), context)
                .security(RequestSecurity.HTTPS)
                .method(HttpMethod.POST)
                .callback(getCallback())
                .tick(1)
                .build()
    }
  private fun getSubject(context: Context): Subject {
        return Subject.SubjectBuilder()
                .context(context)
                .build()
    }
}

This is the separate file that i've created for the tracker and i'm using it like this: 

tracker = SnowplowTracker.getTracker(this)
        tracker?.addGlobalContext(customContext())
tracker?.track(ScreenView.builder().name(javaClass.simpleName).id(UUID.randomUUID().toString()).build())

private fun customContext(): SelfDescribingJson {
        val dataMap: Map<String, Any> = HashMap()

        addToMap("device", "Android", dataMap)
}
logs show that all is sent just like before but i can't track it in our system, maybe it's something wrong on the back-end side? @oguzhanunlu

**Comment by oguzhanunlu** [comment] 2019-11-06 15:40
Hi @SzotsLevente , sorry for late response.

I wanted to reproduce using exactly the same snippet you shared however this isn't valid Java code. I guess you modified before sharing on purpose which invalidated the snippet. Anyway, I noticed that your snippet and our demo apps' relevant section differs only in emitter section. I updated emitter configuration as [here](https://github.com/snowplow/snowplow-android-tracker/blob/global-context-trial/snowplow-demo-app/src/main/java/com/snowplowanalytics/snowplowtrackerdemo/Demo.java#L302-L303) and tried. As before, screen view event which is sent after adding global context has landed in good bucket.

> logs show that all is sent just like before but i can't track it in our system

Which logs do you refer to? If it is logs coming from our SDK, they are printed before events are sent and requests might fail due to various reasons in which case tracker will re-attempt to send same request.

**Comment by SzotsLevente** [comment] 2019-11-07 09:44
@oguzhanunlu it's all written in Kotlin, and it's a valid code.. anyway i've been talking about the callbacks that you've used as well, they show all the data.
so my code doesn't differ from the example you've posted and still there is something that i'm not doing right any tips?

**Comment by oguzhanunlu** [comment] 2019-11-07 10:45
@SzotsLevente As you see I don't know Kotlin, sorry to assume that you'd use Java. Unfortunately our codes are doing the same but we're observing different results. I can't think of anything else at the moment but will let you know if I think of anything.

**Comment by SzotsLevente** [comment] 2019-11-19 11:07
@oguzhanunlu it's weird, i've tried the same code lately and now even the events are sent multiple times, is there any way that we could talk somewhere to clarify few things?

**Comment by goodits** [comment] 2019-11-25 11:29
Hi @SzotsLevente. Sorry we haven't been able to unblock you yet. The next best step may be to re-post on the [Discourse forums](https://discourse.snowplowanalytics.com/), which have a wider community audience - unless you're a Snowplow customer in which case you can reach out to support.

**Comment by AlexBenny** [comment] 2021-03-24 21:45
Closing for inactivity.
The upcoming version 2.0 will introduce some changes in the Global Contexts API.
Further details will be published in the official documentation and in the migration guide.

**Closed by AlexBenny** 2021-03-24 21:45 UTC
