### ISSUE TITLE
Screen ping for the mobile trackers

### ISSUE THREAD

**Issue by ihortom** [snowplow/snowplow-android-tracker#193] opened 2016-04-01 23:44 UTC
Screen ping for the mobile trackers - for discussion. Comes from customer suggestion:

Is there in the SDK a tracker to measure time on screen?

**Comment by jbeemster** [comment] 2016-08-11 17:22
Hey @ihortom, must have missed this one!  At the moment there is not a way to do this.  However we are starting to track the android lifecycle for backgrounding and foregrounding of the application so there is scope here to try and record the time between an activity being created and then destroyed... will require some digging.

**Comment by bogaert** [comment] 2018-03-23 12:02
Discussion thread on iOS: https://github.com/snowplow/snowplow-objc-tracker/issues/275

**Comment by matus-tomlein** [comment] 2023-05-09 13:56
Duplicate of #503

**Closed by matus-tomlein** 2023-05-09 13:56 UTC
Labels: type:enhancement
