### ISSUE TITLE
Add network_type and network_technology to mobile_context

### ISSUE THREAD

**Issue by bernardosrulzon** [snowplow/snowplow-android-tracker#179] opened 2015-12-10 20:15 UTC
Unlike its iOS counterpart, the Android tracker doesn't fill the network_type and network_technology columns on mobile_context. It would be super helpful to see how Wifi and 3G connections influence user behaviour/engagement.

**Comment by bernardosrulzon** [comment] 2015-12-13 17:10
This is a good reference: https://gist.github.com/emil2k/5130324

**Comment by jbeemster** [comment] 2016-02-25 17:45
Closing as duplicate of https://github.com/snowplow/snowplow-android-tracker/pull/180

**Closed by jbeemster** 2016-02-25 17:45 UTC

**Comment by bernardosrulzon** [comment] 2016-02-25 17:46
@jbeemster #179 is the issue, #180 is the PR

**Comment by jbeemster** [comment] 2016-02-25 17:52
@bernardosrulzon we reference the PR as the issue in the CHANGELOG generally.  I will take the code from the PR and merge it as a new commit which closes the PR when we pull it across to master.

**Comment by bernardosrulzon** [comment] 2016-02-25 18:10
ah - that makes a lot of sense. thanks!
